// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqxOf5dJVc6QizmZRgEvml2fBTbPBaDt0',
    appId: '1:260989102264:web:00a0b7bda6dd5f4f382c4d',
    messagingSenderId: '260989102264',
    projectId: 'ems-offbeat',
    authDomain: 'ems-offbeat.firebaseapp.com',
    storageBucket: 'ems-offbeat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE28kw9WGZoCzqALYmSwATsUkyfLZ7AVo',
    appId: '1:260989102264:android:431e1ca7405548a4382c4d',
    messagingSenderId: '260989102264',
    projectId: 'ems-offbeat',
    storageBucket: 'ems-offbeat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMg6bsMw8BaCBf3P-VrD8VqqIaOD6rT_U',
    appId: '1:260989102264:ios:d3c95af9cf8b6185382c4d',
    messagingSenderId: '260989102264',
    projectId: 'ems-offbeat',
    storageBucket: 'ems-offbeat.firebasestorage.app',
    iosBundleId: 'com.offbeatsoftwaresolutions.ems',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMg6bsMw8BaCBf3P-VrD8VqqIaOD6rT_U',
    appId: '1:260989102264:ios:c1df299c9e9c6f31382c4d',
    messagingSenderId: '260989102264',
    projectId: 'ems-offbeat',
    storageBucket: 'ems-offbeat.firebasestorage.app',
    iosBundleId: 'com.example.emsOffbeat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqxOf5dJVc6QizmZRgEvml2fBTbPBaDt0',
    appId: '1:260989102264:web:f0154c62b3461e91382c4d',
    messagingSenderId: '260989102264',
    projectId: 'ems-offbeat',
    authDomain: 'ems-offbeat.firebaseapp.com',
    storageBucket: 'ems-offbeat.firebasestorage.app',
  );
}
